

USE ContosoRetailDW

SELECT 
DateKey
,COUNT(*) AS TOTAL_TRANSACOES
,SUM(SalesQuantity) AS QTDE_DE_VENDAS
,SUM(SalesAmount) AS TOTAL_FATURAMENTO
,AVG(SalesAmount) AS TICKET_MEDIO
,'ONLINE' AS CANAL_DE_VENDA
FROM FactOnlineSales AS ONLINE
GROUP BY DateKey

UNION ALL

SELECT 
F.DateKey
,COUNT(*) AS TOTAL_TRANSACOES
,SUM(F.SalesQuantity) AS QTDE_DE_VENDAS
,SUM(F.SalesAmount) AS TOTAL_FATURAMENTO
,AVG(F.SalesAmount) AS TICKET_MEDIO
,C.ChannelName AS CANAL_DE_VENDA
FROM FactSales as F
INNER JOIN DimChannel AS C ON C.ChannelKey = F.channelKey
GROUP BY F.DateKey, C.ChannelName
ORDER BY CANAL_DE_VENDA

